'use client';
import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { ArrowDownLeft, ArrowUpRight, ArrowLeft, Plus, RefreshCw, FolderKanban, Users, Pencil, Trash2, Wallet, ChartNoAxesCombined, Info, Check, ListFilter, X, Loader2, ChevronRight, BookOpen, History } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { AlertDialog, AlertDialogContent, AlertDialogHeader, AlertDialogTitle, AlertDialogDescription, AlertDialogFooter, AlertDialogCancel } from '@/components/ui/alert-dialog';
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from '@/components/ui/select';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { Table, TableHeader, TableRow, TableHead, TableBody, TableCell } from '@/components/ui/table';
import { RadioGroup, RadioGroupItem } from '@/components/ui/radio-group';
import { Empty, EmptyHeader, EmptyTitle, EmptyDescription } from '@/components/ui/empty';
import { Skeleton } from '@/components/ui/skeleton';
import { Toaster } from '@/components/ui/sonner';
import { toast } from 'sonner';
import { metrics, money, percent } from '@/lib/finance';
import { apiCall, initializeBitrix } from '@/lib/client';
import type { AppState, Entry, Member } from '@/lib/types';

type Modal = 'entry'|'project'|'category'|'member'|null;
const roles:Record<string,string>={manager:'Руководитель',editor:'Редактор',viewer:'Наблюдатель'};
const COLORS=['#1269e9','#6554c0','#049977','#e39b2e','#d85a71','#70849d'];
function initials(name:string) { return name.split(' ').slice(0,2).map(n=>n[0]).join(''); }
function shortDate(date:string) { return new Date(date+'T12:00:00').toLocaleDateString('ru-RU',{day:'numeric',month:'short'}); }
function Choice({value,onChange,items,label,id}:{value:string;onChange:(v:string)=>void;items:{value:string;label:string}[];label:string;id?:string}) {
  return <Select value={value} onValueChange={onChange}><SelectTrigger id={id} className="choice" aria-label={label}><SelectValue placeholder={label}/></SelectTrigger><SelectContent position="popper">{items.map(i=><SelectItem key={i.value} value={i.value}>{i.label}</SelectItem>)}</SelectContent></Select>;
}
function KindControl({kind,onChange}:{kind:string;onChange:(v:'income'|'expense')=>void}) {
  return <RadioGroup value={kind} onValueChange={v=>onChange(v as 'income'|'expense')} className="kind-control" aria-label="Тип операции">{[['income','Доход'],['expense','Расход']].map(([v,label])=><label key={v} className={kind===v?'chosen':''}><RadioGroupItem value={v}/>{v==='income'?<ArrowDownLeft size={18}/>:<ArrowUpRight size={18}/>} {label}</label>)}</RadioGroup>;
}
export default function FinanceApp() {
  const [data,setData]=useState<AppState|null>(null), [mode,setMode]=useState<'demo'|'bitrix'|null>(null);
  const [demoUser,setDemoUser]=useState('demo:1'), [selected,setSelected]=useState('all'), [error,setError]=useState('');
  const [loading,setLoading]=useState(true), [busy,setBusy]=useState(false), [modal,setModal]=useState<Modal>(null), [formError,setFormError]=useState('');
  const [kind,setKind]=useState<'income'|'expense'>('expense'), [categoryId,setCategoryId]=useState(''), [entryProject,setEntryProject]=useState('');
  const [editing,setEditing]=useState<Entry|null>(null), [entryId,setEntryId]=useState(''), [remove,setRemove]=useState<Entry|Member|null>(null);
  const [employee,setEmployee]=useState(''), [memberRole,setMemberRole]=useState('editor'), [directoryNext,setDirectoryNext]=useState<number|null>(0);
  const [from,setFrom]=useState(''), [to,setTo]=useState(''), [tab,setTab]=useState('entries'), [events,setEvents]=useState<any[]>([]), [auditLoading,setAuditLoading]=useState(false), [auditError,setAuditError]=useState('');
  const generation=useRef(0);
  const api=useCallback((path:string,method='GET',payload?:unknown)=>apiCall(path,mode!,demoUser,method,payload),[mode,demoUser]);
  const bootstrap=useCallback(async()=>{setLoading(true);setError('');try{const response=await fetch('/api/config');const config=await response.json();if(!response.ok)throw new Error(config.error);if(config.mode==='bitrix')await initializeBitrix();setMode(config.mode);}catch(e){setError((e as Error).message);setLoading(false);}},[]);
  useEffect(()=>{void bootstrap();},[bootstrap]);
  const reload=useCallback(async(silent=false)=>{
    if(!mode)return;const n=++generation.current;if(!silent)setLoading(true);
    try{const result=await api('/api/state');if(n===generation.current){setData(result);setError('');}}
    catch(e){if(n===generation.current)setError((e as Error).message);}
    finally{if(n===generation.current)setLoading(false);}
  },[mode,api]);
  useEffect(()=>{setData(null);void reload();const interval=window.setInterval(()=>{if(!document.hidden)void reload(true);},30000);const focus=()=>{if(!document.hidden)void reload(true);};document.addEventListener('visibilitychange',focus);return()=>{clearInterval(interval);document.removeEventListener('visibilitychange',focus);++generation.current;};},[reload]);
  const loadAudit=useCallback(async()=>{if(!mode||selected==='all')return;setAuditLoading(true);setAuditError('');try{const response=await api(`/api/projects/${encodeURIComponent(selected)}/audit`);setEvents(response.events);}catch(e){setAuditError((e as Error).message);}finally{setAuditLoading(false);}},[api,mode,selected]);
  useEffect(()=>{setEvents([]);if(tab==='audit')void loadAudit();},[tab,loadAudit]);
  const project=data?.projects.find(p=>p.id===selected);
  const canEdit=selected==='all'?data?.projects.some(p=>p.role!=='viewer'):!!project&&project.role!=='viewer';
  const canManage=project?.role==='manager';
  const canCategory=data?.user.global_role==='admin'||data?.projects.some(p=>p.role==='manager');
  const periodError=!!(from&&to&&from>to);
  const filtered=useMemo(()=>data?.entries.filter(e=>(selected==='all'||e.project_id===selected)&&(!from||e.date>=from)&&(!to||e.date<=to))||[],[data,selected,from,to]);
  const totals=metrics(filtered);
  const team=data?.members.filter(m=>m.project_id===selected)||[];
  const breakdown=(data?.categories||[]).filter(c=>c.kind==='expense').map(c=>({...c,total:filtered.filter(e=>e.category_id===c.id).reduce((s,e)=>s+e.amount,0)})).filter(c=>c.total>0).sort((a,b)=>b.total-a.total);
  function chooseProject(id:string){setSelected(id);setTab('entries');}
  function openEntry(entry?:Entry){setFormError('');setEditing(entry||null);setEntryId(entry?.id||crypto.randomUUID());const type=entry?.kind||'expense';setKind(type);setCategoryId(entry?.category_id||data?.categories.find(c=>c.kind===type)?.id||'');setEntryProject(entry?.project_id||(project&&project.role!=='viewer'?project.id:data?.projects.find(p=>p.role!=='viewer')?.id)||'');setModal('entry');}
  function openModal(value:Modal){setFormError('');setModal(value);if(value==='category')setKind('expense');if(value==='member'){setEmployee('');setMemberRole('editor');}}
  function changeKind(value:'income'|'expense'){setKind(value);setCategoryId(data?.categories.find(c=>c.kind===value)?.id||'');}
  async function save(event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(busy)return;setBusy(true);setFormError('');const f=new FormData(event.currentTarget);
    try{
      if(modal==='entry'){await api(editing?`/api/entries/${encodeURIComponent(editing.id)}`:'/api/entries',editing?'PATCH':'POST',{id:entryId,projectId:entryProject,categoryId,amount:f.get('amount'),date:f.get('date'),note:f.get('note'),...(editing?{version:editing.version}:{})});}
      if(modal==='project'){const r=await api('/api/projects','POST',{name:f.get('name'),client:f.get('client'),description:f.get('description')});chooseProject(r.id);}
      if(modal==='category')await api('/api/categories','POST',{name:f.get('name'),kind});
      if(modal==='member')await api(`/api/projects/${encodeURIComponent(selected)}/members`,'POST',{userId:employee,role:memberRole});
      setModal(null);toast.success('Изменения сохранены');await reload(true);if(tab==='audit')void loadAudit();
    }catch(e){setFormError((e as Error).message);}finally{setBusy(false);}
  }
  async function confirmRemove(){if(!remove||busy)return;setBusy(true);setFormError('');try{
    if('amount'in remove)await api(`/api/entries/${encodeURIComponent(remove.id)}`,'DELETE',{version:remove.version});
    else await api(`/api/projects/${encodeURIComponent(remove.project_id)}/members`,'DELETE',{userId:remove.user_id});
    setRemove(null);toast.success('Изменения сохранены');await reload(true);
  }catch(e){setFormError((e as Error).message);}finally{setBusy(false);}}
  async function importDirectory(){setBusy(true);setFormError('');try{const response=await api('/api/directory','POST',{start:directoryNext||0});setDirectoryNext(response.next);await reload(true);toast.success(`Сотрудников загружено: ${response.count||0}`);}catch(e){setFormError((e as Error).message);}finally{setBusy(false);}}
  const titles={entry:editing?'Изменить операцию':'Новая операция',project:'Новый проект',category:'Новая статья',member:'Участник проекта'};
  return <div className="finance-app"><Toaster richColors position="top-right"/>
    <header className="topbar"><a className="brand" href="/" aria-label="Контур проектов, главная"><span className="brand-mark"><ChartNoAxesCombined size={24}/></span><span>Контур<span className="brand-light"> проектов</span></span></a><div className="topbar-right"><span className="integration-label">Битрикс<span>24</span></span><span className="vertical-rule"/><span className="avatar">{initials(data?.user.name||'К П')}</span><span className="user-name">{data?.user.name||'Финансы команды'}</span></div></header>
    {mode==='demo'&&<div className="demo-bar"><span><strong>Демонстрация</strong><span className="demo-extra"> · Примерные данные, общие для всех демо-сотрудников</span></span><div className="demo-switch"><span>Смотреть как</span><Choice value={demoUser} onChange={v=>{setModal(null);setRemove(null);chooseProject('all');setDemoUser(v);}} label="Демо-сотрудник" items={[{value:'demo:1',label:'Анна · администратор'},{value:'demo:2',label:'Михаил · редактор / руководитель'},{value:'demo:3',label:'Елена · наблюдатель / редактор'},{value:'demo:4',label:'Игорь · редактор'}]}/></div></div>}
    <main className="workspace">
      <div className="page-heading"><div><p className="eyebrow"><FolderKanban size={15}/> УПРАВЛЕНИЕ ПРОЕКТАМИ</p><h1>Финансы проектов</h1><p className="page-caption">Доходы, расходы и результат работы команды</p></div><div className="heading-actions"><Button variant="outline" disabled={!data||!canCategory} onClick={()=>openModal('category')}><BookOpen/> Новая статья</Button><Button disabled={!data} onClick={()=>openModal('project')}><Plus/> Новый проект</Button></div></div>
      {error&&<div className="error-banner" role="alert"><span>{error}</span><Button variant="outline" onClick={()=>mode?reload():bootstrap()}>Повторить</Button></div>}
      {!data? <div aria-busy={loading} aria-label="Загрузка финансов">{loading&&<><div className="kpi-grid">{[1,2,3,4].map(n=><Skeleton key={n} className="h-36 rounded-xl"/>)}</div><Skeleton className="mt-6 h-72 w-full rounded-xl"/></>}{!loading&&!error&&<Empty><EmptyTitle>Загрузка не завершена</EmptyTitle><Button onClick={()=>reload()}>Повторить</Button></Empty>}</div> : <>
      <div className="scope-row"><div className="scope-name"><button className={selected==='all'?'scope-current':'back-link'} onClick={()=>chooseProject('all')}>{selected!=='all'&&<ArrowLeft size={16}/>}Все проекты</button>{project&&<><ChevronRight size={16}/><span>{project.name}</span></>}</div><div className="date-filter"><ListFilter size={16}/><label htmlFor="date-from">Период</label><Input id="date-from" aria-label="Начало периода" type="date" min="2000-01-01" max="2100-12-31" value={from} onChange={e=>setFrom(e.target.value)}/><span>–</span><Input aria-label="Конец периода" type="date" min="2000-01-01" max="2100-12-31" value={to} onChange={e=>setTo(e.target.value)}/>{(from||to)&&<Button variant="ghost" size="icon" aria-label="Сбросить период" onClick={()=>{setFrom('');setTo('');}}><X size={16}/></Button>}</div></div>
      {periodError&&<p className="inline-error" role="alert">Начало периода должно быть раньше окончания.</p>}
      {selected!=='all'&&!project?<Empty><EmptyTitle>Доступ к проекту закрыт</EmptyTitle><Button onClick={()=>chooseProject('all')}>Все проекты</Button></Empty>:<>
      <section className="kpi-grid" aria-label="Финансовые показатели">
        {[{label:'Доходы',value:money(totals.income),hint:'Поступления от клиентов',icon:<ArrowDownLeft/>,cls:'income'},{label:'Расходы',value:money(totals.expenses),hint:'Включая дивиденды',icon:<ArrowUpRight/>,cls:'expenses'},{label:'Прибыль',value:money(totals.profit),hint:'Доходы минус все расходы',icon:<Wallet/>,cls:totals.profit<0?'loss':'profit'},{label:'Рентабельность',value:percent(totals.margin),hint:totals.margin===null?'Нет доходов для расчёта':'Прибыль / доходы × 100%',icon:<ChartNoAxesCombined/>,cls:totals.profit<0?'loss':'margin'}].map(k=><article key={k.label} className={`kpi ${k.cls}`}><div className="kpi-label">{k.label}<span>{k.icon}</span></div><div className="kpi-value">{periodError?'—':k.value}</div><p>{k.hint}</p></article>)}
      </section>
      {selected==='all'&&<section className="project-section"><div className="section-heading"><h2>Проекты <span className="count">{data.projects.length}</span></h2><span>Показатели за выбранный период</span></div><div className="project-grid">{data.projects.map((p,index)=>{const list=filtered.filter(e=>e.project_id===p.id);const s=metrics(list);const people=data.members.filter(m=>m.project_id===p.id);return <button className="project-card" key={p.id} onClick={()=>chooseProject(p.id)}><div className="project-card-top"><span className="project-icon" style={{color:COLORS[index%COLORS.length],background:COLORS[index%COLORS.length]+'12'}}><FolderKanban size={22}/></span><span className={`status-badge ${s.profit<0?'negative':''}`}>{periodError?'Проверьте период':!list.length?'Нет операций':s.profit<0?'Убыток':s.profit>0?'Прибыльный':'Без прибыли'}</span></div><h3>{p.name}</h3><p className="client">{p.client||'Клиент не указан'}</p><div className="project-result"><div><span>Прибыль</span><strong className={s.profit<0?'negative-text':''}>{periodError?'—':money(s.profit)}</strong></div><div><span>Рентабельность</span><strong>{periodError?'—':percent(s.margin)}</strong></div></div><div className="project-card-footer"><div className="avatar-stack">{people.slice(0,3).map(m=><span title={m.name} className="avatar small" key={m.user_id}>{initials(m.name)}</span>)}<span className="people-count">{people.length} в команде</span></div><ChevronRight size={17}/></div></button>;})}</div>{data.projects.length===0&&<Empty><EmptyHeader><EmptyTitle>Начните с первого проекта</EmptyTitle><EmptyDescription>Добавьте проект, участников и первую финансовую операцию.</EmptyDescription></EmptyHeader><Button onClick={()=>openModal('project')}><Plus/> Создать проект</Button></Empty>}</section>}
      <div className="content-grid"><section className="panel operations-panel">
        <div className="panel-heading"><div><h2>{project?.name||'Все операции'}</h2><p>{project?.description||'Доходы и расходы по доступным проектам'}</p></div><Button onClick={()=>openEntry()} disabled={!canEdit}><Plus/> Добавить операцию</Button></div>
        <Tabs value={tab} onValueChange={setTab} className="finance-tabs"><TabsList variant="line"><TabsTrigger value="entries"><Wallet/> Операции <span className="count">{filtered.length}</span></TabsTrigger>{project&&<><TabsTrigger value="team"><Users/> Команда <span className="count">{team.length}</span></TabsTrigger><TabsTrigger value="audit"><History/> История</TabsTrigger></>}</TabsList>
        <TabsContent value="entries">{project?.role==='viewer'&&<div className="permission-note"><Info size={16}/> Вам доступен просмотр финансов этого проекта.</div>}
          {filtered.length>0?<Table className="entry-table"><TableHeader><TableRow><TableHead>Дата / статья</TableHead><TableHead>{project?'Комментарий':'Проект / комментарий'}</TableHead><TableHead>Сотрудник</TableHead><TableHead className="amount-cell">Сумма</TableHead><TableHead><span className="sr-only">Действия</span></TableHead></TableRow></TableHeader><TableBody>{filtered.map(entry=>{const editable=data.projects.find(p=>p.id===entry.project_id)?.role!=='viewer';return <TableRow key={entry.id}><TableCell><div className="entry-article"><span className={`direction ${entry.kind}`}>{entry.kind==='income'?<ArrowDownLeft size={17}/>:<ArrowUpRight size={17}/>}</span><div><strong>{entry.category_name}</strong><small>{shortDate(entry.date)} {entry.date.slice(0,4)}</small></div></div></TableCell><TableCell className="note-cell">{!project&&<strong>{data.projects.find(p=>p.id===entry.project_id)?.name}</strong>}<span>{entry.note||'Без комментария'}</span></TableCell><TableCell><span className="author">{entry.author_name}</span></TableCell><TableCell className={`amount-cell ${entry.kind==='income'?'positive-text':''}`}><strong>{entry.kind==='income'?'+':'−'}{money(entry.amount)}</strong></TableCell><TableCell><div className="row-actions">{editable&&<><Button variant="ghost" size="icon" aria-label={`Изменить: ${entry.category_name}, ${money(entry.amount)}`} onClick={()=>openEntry(entry)}><Pencil size={16}/></Button><Button variant="ghost" size="icon" aria-label={`Удалить: ${entry.category_name}, ${money(entry.amount)}`} onClick={()=>{setFormError('');setRemove(entry);}}><Trash2 size={16}/></Button></>}</div></TableCell></TableRow>;})}</TableBody></Table>:<Empty><EmptyHeader><EmptyTitle>Операций пока нет</EmptyTitle><EmptyDescription>{from||to?'Измените период или добавьте операцию с нужной датой.':'Добавьте первый доход или расход, чтобы увидеть результат проекта.'}</EmptyDescription></EmptyHeader>{canEdit&&<Button variant="outline" onClick={()=>openEntry()}><Plus/> Добавить операцию</Button>}</Empty>}
        </TabsContent>
        <TabsContent value="team"><div className="team-toolbar"><p>Права действуют только в этом проекте.</p>{canManage&&<Button variant="outline" onClick={()=>openModal('member')}><Plus/> Добавить сотрудника</Button>}</div><div className="team-list">{team.map(m=><div className="team-member" key={m.user_id}><span className="avatar">{initials(m.name)}</span><div className="team-person"><strong>{m.name}</strong><span>{roles[m.role]}</span></div>{canManage&&m.user_id!==data.user.id&&<><Button variant="ghost" onClick={()=>{openModal('member');setEmployee(m.user_id);setMemberRole(m.role);}}>Изменить</Button><Button variant="ghost" size="icon" aria-label={`Убрать ${m.name}`} onClick={()=>{setFormError('');setRemove(m);}}><X size={16}/></Button></>}</div>)}</div><p className="permission-note">Руководитель управляет составом команды и операциями. Редактор ведёт операции. Наблюдатель видит показатели и историю.</p></TabsContent>
        <TabsContent value="audit"><div className="team-toolbar"><p>Последние 100 изменений · за всё время</p><Button variant="ghost" onClick={()=>loadAudit()} disabled={auditLoading}><RefreshCw/> Обновить</Button></div>{auditError&&<p className="inline-error" role="alert">{auditError}</p>}{auditLoading?<Skeleton className="h-32 m-5"/>:events.length?<ol className="audit-list">{events.map(ev=>{const after=ev.after_json?JSON.parse(ev.after_json):null;const before=ev.before_json?JSON.parse(ev.before_json):null;const labels:Record<string,string>={entry_create:'Добавлена операция',entry_update:'Изменена операция',entry_delete:'Удалена операция',project_create:'Создан проект',member_save:'Обновлён участник',member_remove:'Участник исключён'};return <li key={ev.id}><span className="audit-marker"><Check size={14}/></span><div><strong>{labels[ev.action]||ev.action}</strong><p>{ev.actor_name} · {new Date(ev.created_at).toLocaleString('ru-RU')}</p>{ev.action.startsWith('entry')?<p>{before?.amount&&<span>{money(before.amount)} → </span>}{ev.action==='entry_delete'?'Удалена из расчётов':money(after?.amount||0)} · {after?.note||before?.note||'Без комментария'}</p>:after?.name&&<p>{after.name}{after.role?` · ${roles[after.role]}`:''}</p>}</div></li>;})}</ol>:<Empty><EmptyTitle>Изменений пока нет</EmptyTitle></Empty>}</TabsContent></Tabs>
        <footer className="panel-footer"><span>Обновлено {new Date(data.serverTime).toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit'})} · каждые 30 секунд</span><Button variant="ghost" size="sm" disabled={loading} onClick={()=>reload(true)}><RefreshCw size={14}/> Обновить</Button></footer>
      </section><aside className="summary-column"><section className="panel expense-panel"><div className="side-heading"><h2>Структура расходов</h2><span>Доля от всех расходов</span></div>{breakdown.length?<><div className="expense-stack" aria-label="Доли статей расходов">{breakdown.map((c,i)=><div key={c.id} style={{width:`${c.total/totals.expenses*100}%`,background:COLORS[i%COLORS.length]}} title={`${c.name}: ${percent(c.total/totals.expenses*100)}`}/>)}</div><div className="expense-list">{breakdown.map((c,i)=><div key={c.id} className="expense-item"><span className="category-dot" style={{background:COLORS[i%COLORS.length]}}/><div><div className="expense-name">{c.name}</div><div className="expense-values"><strong>{money(c.total)}</strong><span>{percent(c.total/totals.expenses*100)}</span></div></div></div>)}</div></>:<p className="side-empty">Расходы появятся после первой операции.</p>}</section>
        <section className="calculation-note"><Info size={19}/><h3>Как считаем результат</h3><p>Учёт по внесённым оплатам, в рублях. Дивиденды включены в расходы по правилам проекта.</p><div className="before-dividends"><span>Прибыль до дивидендов</span><strong>{periodError?'—':money(totals.operatingProfit)}</strong></div><p>Рентабельность = прибыль после дивидендов / доходы × 100%. При нулевом доходе показатель не определяется.</p></section>
      </aside></div></>}
      <div className="workspace-footer"><span>Единый учёт · Рубли · Фактические оплаты</span><span>{data.mode==='demo'?'Демонстрационные данные':'Данные портала Битрикс24'}</span></div>
      </>}
    </main>
    <Dialog open={!!modal} onOpenChange={open=>{if(!open&&!busy)setModal(null);}}><DialogContent className="finance-dialog"><DialogHeader><DialogTitle>{modal?titles[modal]:''}</DialogTitle><DialogDescription>{modal==='entry'?'Укажите факт оплаты. Все участники увидят изменение после обновления.':modal==='member'?'Выберите сотрудника и его права в проекте.':modal==='category'?'Статья будет доступна во всех проектах.':'Создайте проект и затем пригласите команду.'}</DialogDescription></DialogHeader><form key={`${modal}-${editing?.id||entryId}`} onSubmit={save} className="finance-form">
      {modal==='entry'&&<><KindControl kind={kind} onChange={changeKind}/><div className="field"><label htmlFor="entry-project">Проект</label><Choice id="entry-project" value={entryProject} onChange={setEntryProject} label="Проект" items={(data?.projects||[]).filter(p=>p.role!=='viewer').filter(p=>!editing||p.id===editing.project_id).map(p=>({value:p.id,label:p.name}))}/></div><div className="field"><label htmlFor="entry-category">Статья {kind==='income'?'дохода':'расхода'}</label><Choice id="entry-category" value={categoryId} onChange={setCategoryId} label="Статья" items={(data?.categories||[]).filter(c=>c.kind===kind).map(c=>({value:c.id,label:c.name}))}/></div><div className="form-two"><div className="field"><label htmlFor="amount">Сумма, ₽</label><Input id="amount" name="amount" inputMode="decimal" autoFocus required placeholder="0,00" defaultValue={editing?(editing.amount/100).toFixed(2).replace('.',','):''}/></div><div className="field"><label htmlFor="entry-date">Дата оплаты</label><Input id="entry-date" name="date" type="date" required min="2000-01-01" max="2100-12-31" defaultValue={editing?.date||new Date().toLocaleDateString('sv-SE')}/></div></div><div className="field"><label htmlFor="entry-note">Комментарий <span>необязательно</span></label><Textarea id="entry-note" name="note" maxLength={1000} defaultValue={editing?.note||''} placeholder="За что получена или потрачена сумма"/></div>{categoryId&&data?.categories.find(c=>c.id===categoryId)?.expense_class==='distribution'&&<p className="permission-note">Дивиденды уменьшают итоговую прибыль. Прибыль до дивидендов показывается отдельно.</p>}</>}
      {modal==='project'&&<><div className="field"><label htmlFor="project-name">Название проекта</label><Input id="project-name" name="name" required autoFocus maxLength={150} placeholder="Например, внедрение CRM для «Вектор»"/></div><div className="field"><label htmlFor="project-client">Клиент <span>необязательно</span></label><Input id="project-client" name="client" maxLength={150} placeholder="Название компании"/></div><div className="field"><label htmlFor="project-description">Описание <span>необязательно</span></label><Textarea id="project-description" name="description" maxLength={1000} placeholder="Какие работы выполняет команда"/></div></>}
      {modal==='category'&&<><KindControl kind={kind} onChange={setKind}/><div className="field"><label htmlFor="category-name">Название статьи</label><Input id="category-name" name="name" required autoFocus maxLength={100} placeholder={kind==='expense'?'Например, дизайн':'Например, сопровождение'}/></div></>}
      {modal==='member'&&<>{data?.mode==='bitrix'&&<Button type="button" variant="outline" disabled={busy} onClick={importDirectory}><RefreshCw/> {directoryNext?'Загрузить следующих сотрудников':'Обновить список из Битрикс24'}</Button>}<div className="field"><label htmlFor="member-name">Сотрудник</label><Choice id="member-name" value={employee} onChange={v=>{setEmployee(v);setMemberRole(team.find(m=>m.user_id===v)?.role||'editor');}} label="Выберите сотрудника" items={(data?.users||[]).filter(u=>u.id!==data?.user.id).map(u=>({value:u.id,label:u.name}))}/></div><div className="field"><label htmlFor="member-role">Права в проекте</label><Choice id="member-role" value={memberRole} onChange={setMemberRole} label="Роль" items={Object.entries(roles).map(([value,label])=>({value,label}))}/></div><p className="permission-note">{memberRole==='manager'?'Управляет операциями и составом команды.':memberRole==='editor'?'Добавляет, исправляет и удаляет операции.':'Просматривает показатели, операции и историю.'}</p></>}
      {formError&&<p className="inline-error" role="alert">{formError}</p>}<div className="form-actions"><Button type="button" variant="outline" disabled={busy} onClick={()=>setModal(null)}>Отмена</Button><Button type="submit" disabled={busy||(modal==='member'&&!employee)||(modal==='entry'&&(!categoryId||!entryProject))}>{busy?<Loader2 className="animate-spin"/>:<Check/>} {busy?'Сохраняем…':'Сохранить'}</Button></div>
    </form></DialogContent></Dialog>
    <AlertDialog open={!!remove} onOpenChange={open=>{if(!open&&!busy)setRemove(null);}}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>{remove&&'amount'in remove?'Удалить операцию?':'Убрать сотрудника из проекта?'}</AlertDialogTitle><AlertDialogDescription>{remove&&'amount'in remove?`${remove.category_name} · ${money(remove.amount)}. Операция перестанет участвовать в расчётах. Запись об удалении останется в истории.`:'Доступ к проекту будет закрыт. Ранее внесённые операции сохранятся.'}</AlertDialogDescription></AlertDialogHeader>{formError&&<p role="alert" className="inline-error">{formError}</p>}<AlertDialogFooter><AlertDialogCancel disabled={busy}>Отмена</AlertDialogCancel><Button variant="destructive" disabled={busy} onClick={confirmRemove}>{busy?'Сохраняем…':'Удалить'}</Button></AlertDialogFooter></AlertDialogContent></AlertDialog>
  </div>;
}
